@extends('layouts.app')

@section('title', 'Add Labour')
@section('page-title', 'Add Labour')

@section('content')

<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<div class="page-header">
    <div>
        <div class="page-title">Add New Labour</div>
        <div class="page-subtitle">Register a new worker on site</div>
    </div>
    <a href="{{ route('labours.index') }}" class="btn btn-outline"><i class="fas fa-arrow-left"></i> Back</a>
</div>

<div class="card" style="max-width:800px;">
    <div class="card-header">Labour Details</div>
    <div class="card-body">
        <form method="POST" action="{{ route('labours.store') }}">
            @csrf
        {{-- old name and employee id section without autogenerated code --}}
                    {{-- <div class="form-grid-2">
                        <div class="form-group">
                            <label>Full Name *</label>
                            <input type="text" name="name" value="{{ old('name') }}" required placeholder="e.g. Ramesh Kumar">
                        </div>
                        <div class="form-group">
                            <label>Employee ID *</label>
                            <input type="text" name="employee_id" value="{{ old('employee_id') }}" required placeholder="e.g. EMP-001">
                        </div>
                    </div> --}}

{{-- New Section for getting employee id automatically when name is entered --}}
<div class="labour-form">
            <div class="form-grid-2">
                <!-- Full Name -->
                <div class="form-group">
                    <label>Full Name *</label>

                    <input
                        type="text"
                        id="employee_name"
                        name="name"
                        value="{{ old('name') }}"
                        required
                        placeholder="e.g. Ramesh Kumar">
                </div>

                <!-- Employee ID -->
                <div class="form-group">
                    <label>Employee ID *</label>

                    <input
                        type="text"
                        id="employee_id"
                        name="employee_id"
                        value="{{ $employeeId ?? '' }}"
                        readonly
                        required
                        placeholder="Auto generated Employee ID">
                </div>
            </div>

            <div class="form-grid-2">
                <div class="form-group">
                    <label>Category *</label>
                    <select name="category" id='category' required border: 1px solid #e5e7eb; border-radius: 4px; padding: 8px; width: 100%;>
                        <option value="">Select Category</option>
                        @foreach(['Welder','IBR Welder','Electrician','Fitter','Helper','Rigger','Assistant Fitter','Grinder','Taker Welder','Gas Cutter','Khallasi Helper','Visual Grinder','Structure Fitter'] as $cat)
                        <option value="{{ $cat }}" {{ old('category') == $cat ? 'selected' : '' }}>{{ $cat }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label>Phone</label>
                    {{-- <input type="text" name="phone" value="{{ old('phone') }}" placeholder="e.g. 9876543210"> --}}
                    <input
                        type="text"
                        name="phone"
                        value="{{ old('phone') }}"
                        placeholder="e.g. 9876543210"
                        maxlength="10"
                        pattern="[6-9]{1}[0-9]{9}"
                        inputmode="numeric"
                        oninput="this.value = this.value.replace(/[^0-9]/g, '').slice(0,10)">
                </div>
            </div>

            <div class="form-group">
                <label>Address</label>
                <textarea name="address" rows="2" placeholder="Full address">{{ old('address') }}</textarea>
            </div>

            <hr class="divider">
            <div style="font-weight:600;font-size:13px;margin-bottom:14px;color:var(--text-muted);text-transform:uppercase;letter-spacing:1px;">
                <i class=""></i>&nbsp; Wage & Deduction Settings
            </div>

            
    <div class="form-grid-3">

        <!-- Total Salary -->
        <div class="form-group">
            <label>Salary (₹) *</label>

            <input
                type="number"
                id="total_salary"
                name="total_salary"
                placeholder="Enter total monthly salary"
                value="{{ old('total_salary') }}"
                required
                step="0.01"
                min="0">
        </div>

        <!-- Working Days -->
        <div class="form-group">
            <label>Working Days/Month *</label>

            <select id="working_days" name="working_days" required>
                <option value="">Select Days</option>

                @for($i = 26; $i <= 31; $i++)
                    <option value="{{ $i }}">{{ $i }} Days</option>
                @endfor
            </select>
        </div>

            <!-- Daily Wage -->
            <div class="form-group">
                <label>Daily Wage (₹) *</label>

                <input
                    type="number"
                    id="daily_wage"
                    name="daily_wage"
                    placeholder="Auto calculated daily wage"
                    readonly
                    step="0.01">
            </div>
                <div class="form-group">
                    <label>Basic (₹) *</label>

                <input
                    type="number"
                    name="basic_salary"
                    placeholder="Basic Salary"
                    step="0.01">

                </div>  
                <div class="form-group">
                    <label>HRA (₹) *</label>

                    <input
                    type="number"
                    name="hra"
                    placeholder="HRA"
                    step="0.01">
                </div>
                <div class="form-group">
                    <label>Other Allowance (₹) *</label>

                    <input
                    type="number"
                    name="other_allowance"  
                    placeholder="Other Allowance"
                    step="0.01">
                </div>

            <!-- Working Hours -->
            <div class="form-group">
                <label>Working Hours/Day *</label>

                {{-- <select id="working_hours" name="working_hours" required> --}}
                    <select id="working_hours" name="working_hours_per_day" required>
                    <option value="">Select Hours</option>

                    @for($i = 8; $i <= 13; $i++)
                        <option value="{{ $i }}">{{ $i }} Hours</option>
                    @endfor
                </select>
            </div>

            <!-- OT Multiplier -->
            <div class="form-group">
                <label>OT Rate Multiplier *</label>

                <select id="ot_rate_multiplier" name="ot_rate_multiplier" required>
                    <option value="">Select Multiplier</option>

                    <option value="1.5">1.5x</option>
                    <option value="2.0">2x</option>
                </select>
            </div>

            <!-- OT Rate -->
            <div class="form-group">
                <label>OT Rate/Hour (₹) *</label>

                <input
                    type="number"
                    id="ot_rate"
                    name="overtime_rate"
                    placeholder="Auto calculated OT rate per hour"
                    readonly
                    step="0.01">
            </div>

</div>

            <div class="form-grid-3">

    {{-- Joining Date --}}
    <div class="form-group">

        <label>Joining Date *</label>

        <input type="date"
               name="joining_date"
               value="{{ old('joining_date', date('Y-m-d')) }}"
               required>

    </div>


    {{-- Status --}}
    <div class="form-group">

        <label>Status *</label>

        <select name="status"
                id="status"
                required>

            <option value="active"
                {{ old('status') == 'active' ? 'selected' : '' }}>

                Active

            </option>

            <option value="inactive"
                {{ old('status') == 'inactive' ? 'selected' : '' }}>

                Inactive

            </option>

        </select>

    </div>


    {{-- Site --}}
    <div class="form-group">

        <label>Site</label>

        <select name="site_id"
                id="site"
                required>

            <option value="">
                Select Site
            </option>

            @foreach($sites as $site)

            <option value="{{ $site->id }}">

                {{ $site->name }}

            </option>

            @endforeach

        </select>

    </div>


    {{-- Bank --}}
    <div class="form-group">

        <label>Bank Name</label>

        <select name="bank_id"
                id="name"
                required>

            <option value="">
                Select Bank
            </option>

            @foreach($banks as $bank)

            <option value="{{ $bank->id }}"
                {{ old('bank_id') == $bank->id ? 'selected' : '' }}>

                {{ $bank->name }}

            </option>

            @endforeach

        </select>

    </div>


    {{-- Aadhar --}}
    <div class="form-group">

        <label>Aadhar Number</label>

        <input type="text"
               name="Aadhar_Number"
               value="{{ old('Aadhar_Number') }}"
               placeholder="Aadhar number">

    </div>


    {{-- Account --}}
    <div class="form-group">

        <label>Account Number</label>

        <input type="text"
               name="Account_Number"
               value="{{ old('Account_Number') }}"
               placeholder="Bank account number">

    </div>


    {{-- Nominee --}}
    <div class="form-group">

        <label>Nominee Name</label>

        <input type="text"
               name="Nominee_details"
               value="{{ old('Nominee_details') }}"
               placeholder="Enter nominee name">

    </div>


    {{-- Relation --}}
    <div class="form-group">

        <label>Relation</label>

        <select name="relation"
                id="nominee_relation">

            <option value="">
                Select Relation
            </option>

            <option value="Father">Father</option>
            <option value="Mother">Mother</option>
            {{-- <option value="Spouse">Spouse</option> --}}
            <option value="Wife">Wife</option>
            <option value="Husband">Husband</option>    
            <option value="Son">Son</option>
            <option value="Daughter">Daughter</option>
            <option value="Brother">Brother</option>
            <option value="Sister">Sister</option>
            <option value="Guardian">Guardian</option>

        </select>

    </div>


    {{-- IFSC --}}
    <div class="form-group">

        <label>IFSC Code</label>

        <input type="text"
               name="IFSC"
               value="{{ old('IFSC') }}"
               placeholder="IFSC code">

    </div>


    {{-- PAN --}}
    <div class="form-group">

        <label>Pan Card</label>

        <input type="text"
               name="Pan_Card"
               value="{{ old('Pan_Card') }}"
               placeholder="PAN card number">

    </div>


    {{-- ESIC --}}
    <div class="form-group">

        <label>ESIC Number</label>

        <input type="text"
               name="ESIC_Number"
               value="{{ old('ESIC_Number') }}"
               placeholder="ESIC number">

    </div>


    {{-- UAN --}}
    <div class="form-group">

        <label>UAN Number</label>

        <input type="text"
               name="UAN"
               value="{{ old('UAN') }}"
               placeholder="Universal Account Number">

    </div>

</div>


<div style="
    display:flex;
    gap:10px;
    margin-top:20px;
    flex-wrap:wrap;
">

    <button type="submit"
            class="btn btn-primary">

        <i class="fas fa-save"></i>

        Save Labour

    </button>

    <a href="{{ route('labours.index') }}"
       class="btn btn-secondary">

        Cancel

    </a>

</div>
                    

{{-- // Auto calculate daily wage based on total salary and working days --}}
<script>

function calculateRates() {

    let salary = parseFloat($('#total_salary').val()) || 0;

    let workingDays = parseFloat($('#working_days').val()) || 1;

    let workingHours = parseFloat($('#working_hours').val()) || 1;

    let otMultiplier = parseFloat($('#ot_rate_multiplier').val()) || 1;

    // Daily wage
    let dailyWage = salary / workingDays;

    // Hourly rate
    let hourlyRate = dailyWage / workingHours;

    // OT Rate
    let otRate = hourlyRate * otMultiplier;

    // Set values
    $('#daily_wage').val(dailyWage.toFixed(2));

    $('#ot_rate').val(otRate.toFixed(2));
}

$(document).ready(function () {

    // Events
    $('#total_salary').on('input', calculateRates);

    $('#working_days').on('change', calculateRates);

    $('#working_hours').on('change', calculateRates);

    $('#ot_rate_multiplier').on('change', calculateRates);

    // Initial load
    calculateRates();

    // Select2
    $('#category').select2({
    placeholder: "Select Category",
    width: '100%',
    // dropdownParent: $('.staff-form')
    dropdownParent: $('#category').parent()
    });

    $('#name').select2({
        placeholder: "Select Bank",
        width: '100%'
    });

    $('#working_days').select2({
        placeholder: "Select Working Days",
        minimumResultsForSearch: Infinity,
        width: '100%'
    });

    $('#working_hours').select2({
        placeholder: "Select Working Hours",
        minimumResultsForSearch: Infinity,
        width: '100%'
    });

    $('#ot_rate_multiplier').select2({
        placeholder: "Select OT Multiplier",
        minimumResultsForSearch: Infinity,
        width: '100%'
    });

    $('#nominee_relation').select2({
        placeholder: "Select Relation",
        minimumResultsForSearch: Infinity,
        width: '100%'
    });
     $('#site').select2({
        placeholder: "Select Site",
        minimumResultsForSearch: Infinity,
        width: '100%'
    });

    // Only if exists
    if ($('#status').length) {

        $('#status').select2({
            placeholder: "Select Status",
            minimumResultsForSearch: Infinity,
            width: '100%'
        });

    }

});

</script>

@endsection